module.exports = {
  DBCONNFAILED: "Failed to connect to database",
  DBCONNSUCCESS: "Connected to database",
  DBERROR: "Database error",
  SERVERUP: "Server started",
  SERVERDOWN: "Server stopped",
  USEREXISTS: "User already exists",
  USERNOTFOUND: "User does not exist",
  CREDERROR: "Invalid credentials",
  USERCREATED: "User created",
  OBIDCHECK: "ObjectID validation",
  INVALIDPOST: "Invalid credentials",
  PASSREGEX: "^(?=.*[A-Za-z])(?=.*d)[A-Za-zd]{6,50}$",
  MALE: "M",
  FEMALE: "F",
  OTHERS: "O",
};
